# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170330_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('About Me', 'About Me'), ('Portfolio', 'Portfolio'), ('Programming', 'Programming'), ('Spanish', 'Spanish')], max_length=100, null=True),
        ),
    ]
