# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'About Me'), (2, 'Portfolio'), (3, 'Programming'), (4, 'Spanish')], max_length=100, null=True),
        ),
    ]
