# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170402_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'About Me'), (2, 'Portfolio'), (3, 'Programming'), (4, 'Spanish')], null=True),
        ),
    ]
